[package]
name = "ndtree"
version = "0.1.0"
edition = "2021"
categories = ["tree", "quadtree", "octree", "collection", "data-structure"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
